// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVEstJHjdyGQUL0OMORp-zRrRp0y40OBA',
    appId: '1:736425037332:web:3ee96ad17e8468dd48a101',
    messagingSenderId: '736425037332',
    projectId: 'roamly-78bbb',
    authDomain: 'roamly-78bbb.firebaseapp.com',
    storageBucket: 'roamly-78bbb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAf1-0edTzOtO39wGqc5KjASTXS9EROqdI',
    appId: '1:736425037332:android:3869b4f1effe475e48a101',
    messagingSenderId: '736425037332',
    projectId: 'roamly-78bbb',
    storageBucket: 'roamly-78bbb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBI2Nt99RSP2Se2xrsOavU8KLMlHPSupY0',
    appId: '1:736425037332:ios:a0d88359ef44d77348a101',
    messagingSenderId: '736425037332',
    projectId: 'roamly-78bbb',
    storageBucket: 'roamly-78bbb.firebasestorage.app',
    iosBundleId: 'com.example.roamly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBI2Nt99RSP2Se2xrsOavU8KLMlHPSupY0',
    appId: '1:736425037332:ios:a0d88359ef44d77348a101',
    messagingSenderId: '736425037332',
    projectId: 'roamly-78bbb',
    storageBucket: 'roamly-78bbb.firebasestorage.app',
    iosBundleId: 'com.example.roamly',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBVEstJHjdyGQUL0OMORp-zRrRp0y40OBA',
    appId: '1:736425037332:web:367b17cce1e8e3f648a101',
    messagingSenderId: '736425037332',
    projectId: 'roamly-78bbb',
    authDomain: 'roamly-78bbb.firebaseapp.com',
    storageBucket: 'roamly-78bbb.firebasestorage.app',
  );

}